### ISSUE TITLE
Redirect not working

### ISSUE THREAD

**Issue by bert-bruggeman** [bashlk/staticman-netlify-function#5]
Redirect doesn't seem to work on my new project (worked fine on previous projects)

**form.html** (https://fb-bouwteam.netlify.app/contact): 
```
<form method="post" action="https://fb-bouwteam-staticman.netlify.app/.netlify/functions/staticman/fbbouwteam/submissions/master/submissions">
<input type="hidden" name="fields[form]" value="Contactformulier">
<input name="options[redirect]" type="hidden" value="https://fb-bouwteam.netlify.app/contact/#success">
```
**staticman.yml** (the same as previous projects)
```
# Name of the property. You can have multiple properties with completely
# different config blocks for different sections of your site.
# For example, you can have one property to handle comment submission and
# another one to handle posts.
submissions:
  # (*) REQUIRED
  #
  # Names of the fields the form is allowed to submit. If a field that is
  # not here is part of the request, an error will be thrown.
  allowedFields: ['form', 'name', 'email', 'message', 'custom']

  # (*) REQUIRED
  #
  # Name of the branch being used. Must match the one sent in the URL of the
  # request.
  branch: "master"

  # Text to use as the commit message or pull request title. Accepts placeholders.
  commitMessage: "Added submission (Staticman)" # [skip ci]

  # (*) REQUIRED
  #
  # Destination path (filename) for the data files. Accepts placeholders.
  filename: "{@timestamp}-{fields.name_slug}"

  # The format of the generated data files. Accepted values are "json", "yaml"
  # or "frontmatter"
  format: "frontmatter"
  extention: "md"

  # List of fields to be populated automatically by Staticman and included in
  # the data file. Keys are the name of the field. The value can be an object
  # with a `type` property, which configures the generated field, or any value
  # to be used directly (e.g. a string, number or array)
  generatedFields:
    name_slug:
      type: slugify
      options:
        field: name
    date:
      type: date

  # Whether entries need to be appproved before they are published to the main
  # branch. If set to `true`, a pull request will be created for your approval.
  # Otherwise, entries will be published to the main branch automatically.
  moderation: false

  # Name of the site. Used in notification emails.
  name: "Website"

  # Notification settings. When enabled, users can choose to receive notifications
  # via email when someone adds a reply or a new comment. This requires an account
  # with Mailgun, which you can get for free at http://mailgun.com.
  #notifications:
    # Enable notifications
    #enabled: true

    # (!) ENCRYPTED
    #
    # Mailgun API key
    #apiKey: "1q2w3e4r"

    # (!) ENCRYPTED
    #
    # Mailgun domain (encrypted)
    #domain: "4r3e2w1q"

  # (*) REQUIRED
  #
  # Destination path (directory) for the data files. Accepts placeholders.
  path: "submissions/{options.slug}"

  # Names of required fields. If any of these isn't in the request or is empty,
  # an error will be thrown.
  requiredFields: ["email", "name"]

  # List of transformations to apply to any of the fields supplied. Keys are
  # the name of the field and values are possible transformation types.
  transforms:
    message: frontmatterContent

```
